### PR TITLE
[rift] Don't send closure message if notify is turned off

### PR DESCRIPTION
**Pull request by Dav-Git**

### CODE REVIEW

**Comment by Dav-Git** [comment]
Checks failinf for graph... I didn't touch that... weird

**Comment by zephyrkul** [comment]
close_rifts is synchronous, you can't await inside of it

**Comment by Dav-Git** [comment]
Ah whoops, didn't notice. I'll try something tomorrow :)

**Comment by zephyrkul** [comment]
This method of resolving the issue has many more issues beyond what I've already described here, and as such I will not be merging it. I have resolved the issue myself in https://github.com/zephyrkul/FluffyCogs/commit/205242cc0e67bb2b95dd0ea49b26159e71546d98.

**Pull request closed without merging**
